name: Test

on: [push, pull_request]

env:
  CMDC_API_KEY: ${{ secrets.CMDC_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - run: pipenv run isort --recursive --diff
      - run: pipenv run black --check .
      - run: pipenv run flake8 --ignore=E501,E266
      - run: pipenv run pytest
